name: Auto Tag on Version Bump

on:
  push:
    branches:
      - main
    paths:
      - 'manifest.json'
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Get version from manifest
        id: get_version
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version from manifest: $VERSION"

      - name: Check if tag exists
        id: check_tag
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          if git rev-parse "refs/tags/$VERSION" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Tag $VERSION already exists"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Tag $VERSION does not exist"
          fi

      - name: Create and push tag
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$VERSION" -m "Release version $VERSION"
          git push origin "$VERSION"
          echo "Created and pushed tag: $VERSION"

      - name: Tag already exists
        if: steps.check_tag.outputs.exists == 'true'
        run: |
          echo "Tag ${{ steps.get_version.outputs.version }} already exists, skipping tag creation"
